Name:           ros-lunar-teb-local-planner-tutorials
Version:        0.2.2
Release:        0%{?dist}
Summary:        ROS teb_local_planner_tutorials package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/teb_local_planner_tutorials
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-lunar-amcl
Requires:       ros-lunar-map-server
Requires:       ros-lunar-move-base
Requires:       ros-lunar-stage-ros
Requires:       ros-lunar-teb-local-planner
BuildRequires:  ros-lunar-catkin

%description
The teb_local_planner_tutorials package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Fri Jun 15 2018 Christoph Rösmann <christoph.roesmann@tu-dortmund.de> - 0.2.2-0
- Autogenerated by Bloom

* Sun Sep 24 2017 Christoph Rösmann <christoph.roesmann@tu-dortmund.de> - 0.2.1-0
- Autogenerated by Bloom

